### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by MrOrkan** [MrOrkan/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by StanislavLytvynchuk** [comment]
...  After defeating Sagat and M. Bison for the nth time, I’ve decided to downshift my martial arts career a little bit and get into this IT thing ― sensei tells me that there’s a lot of money on the Internet, and a whole lot less getting punched in the face. I’d like to build a little website to market my personal brand, then maybe sell a few t-shirts. ...

**Comment by StanislavLytvynchuk** [comment]
DRAFT DRAFT DRAFT DRAFT DRAFT DRAFT DRAFT DRAFT DRAFT DRAFT DRAFT DRAFT DRAFT DRAFT DRAFT

**Comment by StanislavLytvynchuk** [comment]
LIFE & EDUCATION
To live is to fight and to fight is to live. I started learning fighting at my master Gouken's castle, I was beaten at head way too often to remember when exactly.

LANGUAGES
🇺🇸 ENGLISH 🇨🇳 MANDARIN 🇯🇵 JAPANESE

SKILLS
KARATE ENERGY ATTACK SHORYUKEN WALKING BAREFOOT PLAYING VIDEOGAMES DOING BURGERS MASHING POTATOES COPYWRITING ACTING VOICEOVERS

CHARACTER
NOBLE DIRECT BOLD CONFIDENT DARING SCHIZOPHRENIC DRAMATIC PERSUASIVE IMMEDIATE WISE

LIFE LESSON
You must defeat Sheng Long to stand a chance.

LIKES 😃
GI VEGETABLES BLOOD SMALL MARSHMELLOWS RED COLOR KILLED ENEMY

DISLIKES 😞
BISONS GHOSTS SMARTPHONES SMELL OF SEAFOOD BARBER SHOPS SLEEVES

WANTS 🥺
BE FIT WRITE MORE BOOKS FIND A GIRLFRIEND TO GO TO CINEMA WITH KILL ALL OF AKUMA FAMILY

**Comment by MrOrkan** [comment]
― I do not compete with others, the only competition that challenges me is myself. As a fighter, friend and an employee I am known as contemplative, tortured and driven.
